name: 快看漫画签到

on:
  push:
    branches:
      - master
  schedule:
    - cron: "20 22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Run app
        run: npm install
      - run: node app.js
        env:
          KKMH_COOKIE: ${{ secrets.KKMH_COOKIE}}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
